# config.yaml

worker:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: scipy scikit-learn keras tensorflow==2.0.0-alpha0 dask-ml --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: scipy seaborn scikit-learn keras matplotlib tensorflow==2.0.0-alpha0 dask-ml --upgrade
